version: '3'

services:
  bhasini_remote:
    build:
      context: src/bhasini_remote/.
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
